
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myrs
spec:
  replicas: 3
  selector:
    matchLabels:
      type: webserver
  template:
    metadata:
     name: mypod
     labels:
      type: webserver
    spec:
     containers:
      - name: cl 
        image: nginx
   

    

